# Site settings
title: 디에고의 위키
url: "https://pierceh89.github.io"
baseurl: ""
description: >
    디에고의 개발로그 위키
    그 외 여러가지 기록

# My information
email: pierceh89@gmail.com
author: 디에고
profile: 운동 좋아하는 개발자
# twitter_username: pierceh89
github_username: pierceh89
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10 
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: pierceh89
  shortname: pierceh89
utterances:
  repo: pierceh89/pierceh89.github.io
  issue-term: pathname
  label: Comment
  branch: master

google_analytics:
  ua: UA-73592063-3

  #google_adsense:
  #client: ca-pub-3675948545737694

blame: "https://github.com/pierceh89/pierceh89.github.io/blame/master/_wiki"
edit: "https://github.com/pierceh89/pierceh89.github.io/edit/master/_wiki"
issue: "https://github.com/pierceh89/pierceh89.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
